[package]
edition = "2024"
name = "rp_usb_cdc"
version = "0.1.0"
license = "MIT or Apache-2.0"

[build-dependencies]
regex = "1.11.0"

[dependencies]
cortex-m-rt = "0.7"
defmt = "1"
defmt-rtt = "1"
embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }
embassy-futures = "0.1.2"
embassy-sync = "0.8.0"
embassy-time = { version = "0.5.1" }
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
embedded-io-async = "0.7"
heapless = "0.9.3"
portable-atomic = { version = "1.5", features = ["critical-section"] } # required for static_cell
static_cell = "2"
embassy-usb = { version = "0.6.0", features = ["defmt"] }
embassy-usb-driver = { version = "0.2.2", features = ["defmt"] }
serkey = { path = "../../", features = ["defmt"] }

[target.'cfg( target_arch = "arm" )'.dependencies]
panic-probe = { version = "1", features = ["print-defmt"] }

[target.'cfg( target_arch = "riscv32" )'.dependencies]
panic-halt = { version = "1.0.0" }

[target.thumbv6m-none-eabi.dependencies]
embassy-rp = { version = "0.10.0", features = [
    "time-driver",
    "critical-section-impl",
    "rp2040",
    "binary-info",
    "defmt",
    "unstable-pac",
] }

[target.riscv32imac-unknown-none-elf.dependencies]
embassy-rp = { version = "0.10.0", features = [
    "time-driver",
    "critical-section-impl",
    "rp235xa",
    "binary-info",
    "defmt",
    "unstable-pac",
] }

[target."thumbv8m.main-none-eabihf".dependencies]
embassy-rp = { version = "0.10.0", features = [
    "time-driver",
    "critical-section-impl",
    "rp235xa",
    "binary-info",
    "defmt",
    "unstable-pac",
] }
